services:
  db:
    image: postgres
    container_name: teste-db-pix
    environment:
      - POSTGRES_DB=testedbpixmessage
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=mypwd
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
  app:
    image: img-app-pix
    container_name: teste-app-pix
    command: >
      sh -c "npx prisma migrate deploy && npm run dev"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge
